Shop
AlexMandic6/bike-shop pull request #9
Opened 2021-11-05 14:29 UTC by AlexMandic6

2021-11-05 15:13 UTC, AlexMandic6 commented
When was making shop grid responsive, some things are hardcoded to match the design. Maybe overcomplicated this a bit. :)

2021-11-08 09:27 UTC, todorovicj86 commented on src/js/index.js
> +import '../styles/main.scss';
We never import styles to js, only js-files

2021-11-09 08:00 UTC, todorovicj86 requested changes

2021-11-09 08:00 UTC, todorovicj86 commented on src/styles/layout/_text-banner.scss
>  .text-banner-container {
I left the comment in your previous PR regarding the BEM. Please take a look at those comments, so I avoid add the same thing multiple times
![image](https://user-images.githubusercontent.com/44524274/140884885-f4d27d38-ad88-41a4-a567-00c55e5730a8.png)

2021-11-09 13:26 UTC, AlexMandic6 commented on .gitignore
> +dist/
Resolved.

2021-11-09 13:30 UTC, AlexMandic6 commented on package.json
> +    "start": "cross-env webpack-cli serve --mode development"
Resolved

2021-11-09 13:34 UTC, AlexMandic6 commented on src/index.html
> +                <li class="nav__item nav__item-span">
Only way i found to work without using additional elements in html, extra classes or JS manipulation is this selector:
:not(.nav__item-logo):not(:first-child):not(.nav__item-logo + .nav__item)::before 
;D

2021-11-09 13:35 UTC, AlexMandic6 commented on src/index.html
> +                <svg class="card-svg">
Resolved

2021-11-09 13:35 UTC, AlexMandic6 commented on src/styles/layout/_hero.scss
> +        background-size: cover;
Resolved

2021-11-09 13:36 UTC, AlexMandic6 commented on src/styles/layout/_slide.scss
> +    height: 12px!important;
Resolved

2021-11-09 13:36 UTC, AlexMandic6 commented on src/styles/layout/_text-banner.scss
>  .text-banner-container {
Resolved

2021-11-09 13:49 UTC, AlexMandic6 commented on src/index.html
> +                    <div class="slide-container">
Resolved

2021-11-09 13:54 UTC, AlexMandic6 commented on src/index.html
> +            <img class="subscribe__logo" src="./img/logo.png" alt="Company Logo">
It says in specs that subscription logo should not be clickable, its a bit strange i know.

![Untitled](https://user-images.githubusercontent.com/60902831/140936408-18ac24a7-97a8-416e-8acd-21773ab6ef4e.png)

2021-11-09 13:56 UTC, AlexMandic6 commented on src/index.html
> +            <button class="btn btn--black" type="button">Discover the shop</button>
Resolved

2021-11-09 15:08 UTC, AlexMandic6 commented on src/styles/base/_typography.scss
> +@font-face {
resolved

2021-11-09 15:12 UTC, AlexMandic6 commented on src/styles/components/_button.scss
> +    padding: 1rem 2rem;
resolved

2021-11-09 15:12 UTC, AlexMandic6 commented on src/styles/layout/_contact.scss
> +    & .btn--green {
resolved

2021-11-09 15:16 UTC, AlexMandic6 commented on src/styles/layout/_gallery.scss
> +.gallery__image.hide-on-md-screen {
resolved

2021-11-09 15:22 UTC, AlexMandic6 commented on src/styles/layout/_header.scss
> +    }
resolved

2021-11-09 15:27 UTC, AlexMandic6 commented on src/styles/layout/_footer.scss
> +    height: 250px;
deleted fixed height which was just for testing but forgot to delete :)
Added more padding to compensate for that

2021-11-09 15:45 UTC, AlexMandic6 commented on src/index.html
> +                    <img class="shop-grid-img" src="./img/shop/bike-seats.png" alt="Bike seat">
resolved

2021-11-10 11:57 UTC, todorovicj86 approved these changes

2021-11-10 12:10 UTC, merged